
# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: spittet/node-mongodb

#pipelines:
  #default:
    #- step:
        #script: # Modify the commands below to build your repository.
          #- npm install
          #- service mongod start
          #- npm test

image: ruby:2.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.

  branches:
      master:
          - step:
              script:
                  - gem install dpl
                  - dpl --provider=heroku --app=afro-programmers --api-key=0bff7c14-be00-4dec-9c2c-49af7e35ad71
